GenSpectrum/LAPIS

server/src/main/java/ch/ethz/lapis/api/DataVersionService.java, server/src/main/java/ch/ethz/lapis/api/SampleService.java, server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleController.java, server/src/main/java/ch/ethz/lapis/api/entity/AAMutation.java, server/src/main/java/ch/ethz/lapis/api/entity/NucMutation.java, server/src/main/java/ch/ethz/lapis/api/exception/OutdatedDataVersionException.java, server/src/main/java/ch/ethz/lapis/api/query/BiOp.java, server/src/main/java/ch/ethz/lapis/api/query/GisaidClade.java, server/src/main/java/ch/ethz/lapis/api/query/NextstrainClade.java, server/src/main/java/ch/ethz/lapis/api/query/PangoQuery.java, server/src/main/java/ch/ethz/lapis/api/query/Single.java, server/src/main/java/ch/ethz/lapis/api/query/VariantQueryExpr.java, server/src/main/java/ch/ethz/lapis/api/query2/Database.java, server/src/main/java/ch/ethz/lapis/api/query2/QueryEngine.java, server/src/main/java/ch/ethz/lapis/api/query2/QueryExpr.java, server/src/main/java/ch/ethz/lapis/api/query2/StringValue.java
By implementing an in-memory data store and query engine, data filtering and aggregation is now much faster in many cases. For mutation-defined variants with many sequences, quick tests showed a 10-30x speedup.
The query engine is currently only used by the "aggregated" endpoint. Others should follow.
=> Implement an in-memory query engine and use it for /aggregated

docs/developer/getting_started.md, server/.gitignore, server/config.yml.example, server/startServer.sh
This seems more convenient than storing an example config in the docs.
=> provide example config.yml

docs/source/tutorials/developers_and_maintainers/setup_monkeypox_instance.rst, server/build.gradle, server/src/main/java/ch/ethz/lapis/LapisMain.java, server/src/main/java/ch/ethz/lapis/core/ConfigurationManager.java, server/src/main/java/ch/ethz/lapis/core/Utils.java, server/src/test/java/ch/ethz/lapis/core/ConfigurationManagerTest.java, server/src/test/resources/config.test.yml
Reading the config from environment variables is unused -> remove it.
Reading the config thus effectively becomes a one-liner, making snakeyaml obsolete, because we can simply use jackson with it's yaml module.
@chaoran-chen The config files for the productive servers need to be adapted, too, they are probably not stored in this repo, are they?
=> refactor: simplify reading the config

server/build.gradle
I found no usages of org.apache.commons:commons-text -> remove the dependency.
=> refactor: remove unused dependency org.apache.commons:commons-text

server/build.gradle
A newer minor version is incompatible as this PR shows: https://github.com/GenSpectrum/LAPIS/pull/100
=> let Spring Boot manage the version of jackson-dataformat-yaml

lapis2/docker-compose.yml, lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/AggregatedModelTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloFilterTest.kt, siloLapisTests/test/aggregatedQueries/pangoLineageIsB_1_1_7.json, siloLapisTests/test/aggregatedQueries/pangoLineageIsB_1_1_7endingWithDotIncludingSublineages.json, siloLapisTests/test/aggregatedQueries/pangoLineageIsB_1_1_7includingSublineages.json
resolves #201 
This depends on https://github.com/GenSpectrum/LAPIS-SILO/pull/64.
=> fix: correctly map PangoLineageEquals filters

lapis2/build.gradle
It is no longer necessary, see https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/102#issuecomment-1503078476.
=> build: remove workaround in build.gradle

lapis2/build.gradle
Fixes bug, which was introduced by BellSoft Liberica 10.1.0, which does no longer support jvm 19. Thus the docker file could no longer be created.
The jvm for `compileKotlin` is still at version 19, because the current version (1.8.20) of `org.jetbrains.kotlin.jvm` does not support jvm 20 yet
=> fix building with gradlew bootBuildImage

lapis2/build.gradle, lapis2/src/main/antlr/org/genspectrum/lapis/model/variantqueryparser/VariantQuery.g4, lapis2/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryFacade.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt, lapis2/src/test/resources/config/testDatabaseConfig.yaml, lapis2/src/test/resources/config/testDatabaseConfigWithoutFeatures.yaml, siloLapisTests/test/aggregatedQueries/complexVariantQuery.json, siloLapisTests/test/aggregatedQueries/variantQuery.json, siloLapisTests/testDatabaseConfig.yaml
Resolves #193 
The generalization of the variant query will be part of #130. Right now the Silo filter columns are hardcoded.
=> Implement advanced variant queries for SARS-COV-2

lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisRequest.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFieldsDeserializerTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt, siloLapisTests/test/aggregated.spec.ts, siloLapisTests/test/details.spec.ts, siloLapisTests/test/nucleotideMutations.spec.ts
=> Details endpoint

lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/OrderByField.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt, siloLapisTests/test/aggregated.spec.ts, siloLapisTests/test/details.spec.ts, siloLapisTests/test/nucleotideMutations.spec.ts
resolves #290
Please also check that the Swagger UI is correct and useful.
=> feat: implement orderBy, limit and offset

server/src/main/java/ch/ethz/lapis/api/SampleService.java, server/src/main/java/ch/ethz/lapis/api/entity/req/OrderAndLimitConfig.java
This small PR for **LAPIS v1** adds a limited version of `offset` to the `/details` endpoint that only works if no sorting is specified, and it makes `limit` for details much faster.
(fyi @fengelniederhammer, @JonasKellerer)
=> feat(lapis1): implement offset and make limit faster

lapis2/build.gradle, lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CsvWriter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/OperationsSorter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SpecialProperties.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/util/CachedBodyHttpServletRequest.kt, lapis2/src/main/resources/public/error/404.html, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/OperationsSorterTest.kt, siloLapisTests/.gitignore, siloLapisTests/test/details.spec.ts
resolves #284 
resolves #129 
I implemented the idiomatic version via the accept header and mapped the `dataFormat` field to produce a different header.
=> feat: make it possible to return data from /details as CSV and TSV

lapis2/src/main/kotlin/org/genspectrum/lapis/CorsConfiguration.kt
We should think about whether and how we want to make this configurable. #406 is an alternative, but I think we might not want to have it in the database config.
=> feat: configure CORS - allow all origins

lapis2-docs/src/content/config.ts
@chaoran-chen was there a specific reason why you added this collection? Currently Astro shows the warning:
"11:08:36 [WARN] [content] The i18n collection is defined but no content/i18n folder exists in the content directory. Create a new folder for the collection, or check your content configuration file for typos."
=> chore(docs): we don't need internationalization #376

lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
The endpoint returned an object like:
`{
mutation: 
count: 
proportion:
header: ["mutation", "count", "proportion]
}`
This PR should fix, that the header is not returned.
=> fix: remove header output from mutations and insertion endpoints

siloLapisTests/test/alignedNucleotideSequence.spec.ts, siloLapisTests/test/aminoAcidInsertions.spec.ts, siloLapisTests/test/aminoAcidSequence.spec.ts, siloLapisTests/test/details.spec.ts, siloLapisTests/test/nucleotideInsertions.spec.ts
Due to https://github.com/GenSpectrum/LAPIS-SILO/pull/215
=> fix: e2e tests with new silo ordering of insertions and mutations

lapis2-docs/.gitignore, siloLapisTests/test/aminoAcidMutations.spec.ts
SILO now correctly shows deletions as mutations https://github.com/GenSpectrum/LAPIS-SILO/pull/236. This changes our e2e tests. This PR should fix them.
=> fix: update e2e tests: deletions are also mutations (from SILO)

lapis2-docs/astro.config.mjs, lapis2-docs/src/content/docs/concepts/request-id.mdx, lapis2-docs/tests/docs.spec.ts, lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/logging/RequestId.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/util/CachedBodyHttpServletRequest.kt, lapis2/src/main/resources/logback.xml, lapis2/src/test/resources/logback-test.xml, siloLapisTests/test/requestId.spec.ts
=> feat: implement a request id to trace requests

lapis2-docs/playwright.config.ts, siloLapisTests/test/details.spec.ts
There is a ticket to fix the time the e2e tests take: #603
=> fix: end to end tests failing due to timeout and new pango lineage alias in return

lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DownloadAsFileFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/util/CachedBodyHttpServletRequest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
Before, `intersect` was called on a JsonNode, which did not work as expected.
=> fix: allow access in authorized mode when `fields` is specified non-fine-grained

.idea/runConfigurations/LapisV2Protected.xml, lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt, siloLapisTests/testData/protectedTestDatabaseConfig.yaml
The result will not be of much use, since you only get all primary keys, but no additional information. This is required for the UShER integration of cov-spectrum.
resolves #623
=> feat: allow that `fields` only contains the primary key in protected mode

lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
This resolves the issue mentioned in https://github.com/GenSpectrum/cov-spectrum-website/pull/895
Here the query contained more elements in the n-of query than the size of n.
=> fix: exact n of query with more elements than n

lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt
Some proxies such as Traefik will throw an error when the Transfer-Encoding header is present twice. We shouldn't set the header ourselves, but leave that to Tomcat (which also makes sure that the chunking is done correctly). Instead, prevent setting a content length when the response is compressed.
related: #600 
resolves #
=> fix: don't set Transfer-Encoding twice

lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
people sometimes send very long variant queries that resulted in very deeply nested expressions
=> refactor: flatten mapped variant queries

lapis2/src/main/kotlin/org/genspectrum/lapis/CorsConfiguration.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
See https://javascript.info/fetch-crossorigin#response-headers.
> To grant JavaScript access to any other response header, the server must send the Access-Control-Expose-Headers header.
=> feat: make headers accessible to browser despite CORS

lapis2/src/main/kotlin/org/genspectrum/lapis/CorsConfiguration.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DownloadAsFileFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/Headers.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceController.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/logging/RequestId.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt, siloLapisTests/test/common.spec.ts, siloLapisTests/test/common.ts
=> feat: set Content-Type header to application/gzip|zstd when the compression property in the request was set

lapis2/build.gradle, lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/scheduler/DataVersionCacheInvalidator.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/main/resources/application.properties, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt, lapis2/src/test/resources/logback-test.xml
Also make sure to invalidate the cache when SILO has a new data version
resolves #137
=> feat: implement a request cache for mutation and insertion queries

lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
This matter when LAPIS is operated behind a proxy that has a URL prefix
=> fix: consider context path in Swagger UI link

lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, siloLapisTests/test/details.spec.ts
In https://github.com/GenSpectrum/LAPIS-SILO/pull/354 SILO no longer returns insertions on the details endpoint. This is now also in LAPIS
=> fix: details does no longer return insertions

lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CsvWriter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt, siloLapisTests/test/aggregated.spec.ts
=> fix: write empty string to CSV/TSV for null values

lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/logging/RequestContext.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
resolves #717
Tests on a medium-sized data set (3552 sequences):
I measured request times of /sample/unalignedNucleotideSequences:
- uncompressed: 1300 ms, 65 MB
- gzip compressed: 3100 ms (before: 14 s), 8 MB
- zstd compressed: 970 ms (before: 7.4 s), 342 kB
I tested this using the Ebola dataset from Loculus. I pushed it to a branch: https://github.com/GenSpectrum/LAPIS/tree/ebolaTestData
=> download compression is too slow

.gitignore, lapis2/.gitignore, lapis2/README.md, lapis2/build.gradle, lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt, lapis2/src/main/resources/logback.xml
resolves #692
I also included a link to GitHub issues in the LAPIS responses and some info that should help us look for the correct log files. The info is included in all responses, but will be most helpful in analysing error messages. Responses will look like this: 
```json
{
"error": {
"type": "about:blank",
"title": "Internal Server Error",
"status": 500,
"detail": "Could not connect to silo: class java.net.ConnectException null"
},
"info": {
"dataVersion": null,
"requestId": "dfb342ea-3607-4caf-b35e-9aba75d06f81",
"requestInfo": "sars_cov-2_minimal_test_config on localhost at 2024-04-04T12:14:49.420620237",
"reportTo": "Please report to https://github.com/GenSpectrum/LAPIS/issues in case you encounter any unexpected issues.Please include the request ID and the requestInfo in your …
```
=> 692 put logs into file again

lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
=> feat(lapis2)!: read data from SILO as NDJSON

lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt
resolves #738
Chrome now supports zstd compression, so it will set `Accept-Encoding: gzip, deflate, br, zstd`. In that case, we should prefer zstd, because it's usually faster and has better compression ratios.
=> fix(lapis2): prefer zstd over gzip

lapis2/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/DummySequenceFilterFields.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt, lapis2/src/test/resources/config/testDatabaseConfig.yaml, siloLapisTests/test/aggregatedQueries/filterByBoolean.json, siloLapisTests/test/aggregatedQueries/groupByBoolean.json, siloLapisTests/test/details.spec.ts, siloLapisTests/testData/protectedTestDatabaseConfig.yaml, siloLapisTests/testData/small_metadata_set.tsv, siloLapisTests/testData/testDatabaseConfig.yaml
resolves #740
- ~~[ ] All necessary documentation has been adapted.~~ -> #734
=> feat(lapis2): implement boolean columns

.commitlintrc.js
dependabot sometimes creates very long lines in commit messages. Let's just ignore it.
See https://github.com/GenSpectrum/LAPIS/pull/753.
=> chore(root): disable body-max-line-length commit lint

.github/workflows/lapis2.yml, .github/workflows/test.yml
The tests show a notice:
> Deprecation warnings
> This job uses deprecated functionality from the gradle/gradle-build-action action. Follow the links for upgrade details.
> 
>     [The action `gradle/gradle-build-action` has been replaced by `gradle/actions/setup-gradle`](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle)
>     [Using the action to execute Gradle via the `arguments` parameter is deprecated](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated)
I followed:
https://github.com/gradle/actions/blob/90f1de055606f0041bed57fdbee974a43650e639/docs/deprecation-upgrade-guid …
=> chore(github-actions): replace deprecated grad-build-action

lapis2-docs/src/components/FiltersTable/FiltersTable.astro, lapis2-docs/src/content/docs/concepts/pango-lineage-query.mdx, lapis2-docs/src/content/docs/concepts/request-methods.mdx, lapis2-docs/src/content/docs/concepts/response-format.mdx, lapis2-docs/src/content/docs/concepts/variant-query.mdx, lapis2-docs/src/content/docs/getting-started/introduction.mdx, lapis2-docs/src/content/docs/references/additional-request-properties.mdx, lapis2-docs/src/content/docs/references/introduction.mdx, lapis2-docs/tests/docs.spec.ts
Otherwise the following happens:
- Be on page, e.g. /references/filters
- Click on link that ends with slash, e.g. `../concepts/pango-lineage-query/`
- now you are on /concepts/pango-lineage-query/
- clicking another relative link, e.g. ``../concepts/variant-query` will result in wrong target, in this case /concepts/concepts/variant-query
=> fix(lapis2-docs): relative links must not end with a `/`

lapis2/src/main/kotlin/org/genspectrum/lapis/scheduler/DataVersionCacheInvalidator.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
Currently, LAPIS might still return cached data.
This was an accidental discovery while working on CoV Spectrum while SILO crashed.
=> feat(lapis2): clear cache when SILO is restarting

lapis2/src/main/antlr/org/genspectrum/lapis/model/variantqueryparser/VariantQuery.g4, lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryFacade.kt, lapis2/src/main/kotlin/org/genspectrum/lapis/request/MaybeMutationWrapper.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidMutationTest.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideMutationTest.kt, siloLapisTests/test/aggregated.spec.ts
resolves #797
* Breaking change: throw "bad request" when there is unmatched variant query parser input
* Stop logging unmatched parser input to stdout.
* make "maybe" case-insensitive in both, variant queries and normal mutation filters
=> make maybe mutation queries case insensitive

lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt, lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, siloLapisTests/test/aggregated.spec.ts
Together with #797 this should fix the reported issue.
resolves #798
=> fix(lapis2): only accept a single variant query in a request

lapis2/.dockerignore, lapis2/Dockerfile, lapis2/entrypoint.sh
- **chore(lapis2): use eclipse-temurin instead of deprecated openjdk image**
- **feat(lapis2): use entrypoint.sh to allow passing JVM_OPTS through env variable**
resolves #821
=> feat(lapis2): Use entrypoint.sh as entrypoint in dockerfile to allow passing JVM_OPTS

.github/workflows/changelog-preview.yml
=> ci(github-actions): dependabot needs explicit PR write permissions in the Preview Changelog workflow

README.md, lapis-docs/README.md, lapis-docs/test-docker-compose.yml, lapis/README.md
I tried to improve the READMEs with regard to the release, focussing more on users that should understand what LAPIS is and how to use it.
=> docs(root): improve README, try to focus more on potential users

lapis-e2e/test/aggregated.spec.ts, lapis-e2e/test/aggregatedQueries/basicStringSearch.json, lapis-e2e/testData/multiSegmented/testDatabaseConfig.yaml, lapis-e2e/testData/singleSegmented/protectedTestDatabaseConfig.yaml, lapis-e2e/testData/singleSegmented/testDatabaseConfig.yaml, lapis/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt, lapis/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis/src/test/kotlin/org/genspectrum/lapis/DummySequenceFilterFields.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
resolves #898
resolves #901 
Users can now filter for all string columns using regular expressions. Users can decide between a string equals filter using the current notation `"myMetadata": "searchedValue"`. When users want to search using regex, they need to append `$regex` to the metadata field name eg. `"myMetadata$regex": "someRegex"`.
The string columns which support regex search can be configured using the option `lapisAllowsRegexSearch`. Per default it is turned off.
- This will be done in #900 
- The swagger already has the correct values for the example. Only the schema could be refined to include information about the search, see #903
=> feat(lapis): regex filtering for string columns #898

lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
=> feat(lapis): throw error when filtering by "equals" and "regex" for the same string field

lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
=> feat(lapis): hint to which regex syntax is used in Swagger docs

.github/workflows/changelog-preview.yml, .github/workflows/commitlint.yml, lapis-docs/src/components/FiltersTable/getFilters.tsx, lapis-docs/src/components/QueryGenerator/FiltersSelection.tsx, lapis-docs/src/content/docs/concepts/string-search.mdx, lapis-e2e/test/aggregated.spec.ts, lapis-e2e/test/aggregatedQueries/basicStringSearch.json, lapis/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis/src/test/kotlin/org/genspectrum/lapis/DummySequenceFilterFields.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
resolves #908
This PR changes the delimiter symbol of the string search from the `$` sign to a `.` sign. This symbol is not specially encoded in urls. For me this worked on webkit, curl, firefox and chrome. 
Some tools which use ts, like openapi-genereator-cli, have a problem with the dot, since it can not be used in a variable name. The $ sign can be used there. However, kotlin cant use either of them. So this might not an argument for or against this change.
The documentation needs to be changed, but this needs to wait for #906.
=> feat(lapis): use dot symbol as regex separator #908

lapis/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
=> feat(lapis): omit sequences with `null` values in unaligned fasta downloads

README.md
=> docs(root): document that regex support in LAPIS (as of 0.2.10) requires at least SILO 0.2.14

lapis-e2e/test/unalignedNucleotideSequence.spec.ts
Something in the latest bugfixes in SILO must have changed the order (the test does not enforce any order).
=> test(lapis-e2e): fix e2e tests

lapis-docs/src/content/docs/maintainer-docs/tutorials/start-lapis-and-silo.mdx
The expected names of sequence files changed in LAPIS-SILO 0.2.13 from using names (e.g. nuc_main.fasta) to using indexes (nuc_0.fasta).
Related-to: <https://github.com/GenSpectrum/LAPIS-SILO/pull/529>
=> fix(lapis-docs): Sequence file naming scheme uses indexes now not names

lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloUris.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloUrisTest.kt
=> feat(lapis): abort on startup when silo url has invalid syntax

lapis-docs/src/content/docs/index.mdx, lapis-docs/tests/docs.spec.ts
relative links must not end with `/`, so that other relative links on those pages will work In this case, the link `[this tutorial](../maintainer-docs/tutorials/start-lapis-and-silo)` on `/getting-started/introduction` did not work, because when coming from the landing page, you were actually on `/getting-started/introduction/`.
resolves #
=> fix(lapis-docs): fix link on landing page

lapis-docs/tests/docs.spec.ts
As a follow-up to #963, I thought this might be good, because we rely on the default not found page.
=> Test finding not found page

lapis-docs/src/content/docs/maintainer-docs/references/database-configuration.mdx, lapis/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfigValidator.kt, lapis/src/test/kotlin/org/genspectrum/lapis/LapisApplicationTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigValidatorTest.kt, lapis/src/test/resources/config/invalidTestDatabaseConfig.yaml
also validate that `lapisAllowsRegexSearch`-fields are of type string
resolves #976
=> validate that metadata fields do not contain the reserved character `.`

lapis/src/main/resources/logback.xml, lapis/src/test/resources/logback-test.xml
Instead of `<layout><pattern></pattern></layout>` we now have to use `<encoder><pattern></pattern></encoder>`.
https://logback.qos.ch/codes.html#layoutInsteadOfEncoder
resolves #972
=> fix(lapis): get rid of logger config deprecation warnings in the log

lapis-docs/Dockerfile, lapis-docs/astro.config.mjs, lapis-docs/src/config.ts, lapis-docs/src/content/docs/concepts/pango-lineage-query.mdx, lapis-docs/src/content/docs/concepts/string-search.mdx, lapis-docs/src/content/docs/concepts/variant-query.mdx, lapis-docs/src/content/docs/getting-started/generate-your-request.mdx, lapis-docs/src/content/docs/references/database-config.mdx, lapis-docs/src/content/docs/references/fields.mdx, lapis-docs/src/content/docs/references/filters.mdx, lapis-docs/src/content/docs/references/open-api-definition.mdx, lapis-docs/src/content/docs/references/reference-genomes.mdx
resolves #928
This also fixes pango lineage docs (we can't be sure anymore which lineage fields are pango lineages).
Also, all sections are now always available.
=> mark sections of the docs that are generated from the config

.github/workflows/lapis-docs.yml, .github/workflows/lapis.yml, .github/workflows/release-lapis.yml, lapis-docs/Dockerfile, lapis-docs/astro.config.mjs, lapis-e2e/test/common.spec.ts, lapis-e2e/test/common.ts, lapis-e2e/test/info.spec.ts, lapis/Dockerfile, lapis/src/main/kotlin/org/genspectrum/lapis/LapisApplication.kt, lapis/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt, lapis/src/main/kotlin/org/genspectrum/lapis/config/LapisVersion.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/InfoController.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/LapisInfoResponseBodyAdvice.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/InfoControllerTest.kt
This works by reading a `version.txt` from `./`
* locally, the version should be unspecified
* for branch builds, the version should be the commit hash
* for released versions, the version should be the semver tag
=> feat(lapis): add LAPIS version to info response

lapis/src/main/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceController.kt
In the context of https://github.com/loculus-project/loculus/issues/3388
This will simply show no endpoint to download nucleotide sequences when there are none in the reference genomes. Without this change, it shows the single segmented endpoints that throw index out of bounds exceptions:
https://github.com/GenSpectrum/LAPIS/blob/c6f625e22074731e12f6cdbcb68344350e65503e/lapis/src/main/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceController.kt#L109
=> fix(lapis): don't show the single segmented sequence download when there are no nucleotide sequences

README.md, lapis-e2e/test/info.spec.ts, lapis-e2e/test/lineageDefinition.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/InfoController.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloUris.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
resolves #1034
- Do we want to mention this specifically in the LAPIS docs?
=> feat(lapis): expose the lineage definition files used by SILO

lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DataFormatParameterFilter.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDataFormatTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceControllerTest.kt
=> fix(lapis): reject unknown data formats

lapis-e2e/test/aminoAcidMutations.spec.ts, lapis-e2e/test/nucleotideMutations.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
=> feat(lapis): pass through `coverage` from SILO in mutation endpoints

lapis/src/main/resources/logback.xml
The log files on the server were piling up. I think we can safely delete old ones.
https://logback.qos.ch/manual/appenders.html#tbrpMaxHistory
=> fix(lapis): only keep old log files for 30 days

.idea/runConfigurations/LapisOpen.xml, lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithStopCodon.json, lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithWildcard.json, lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithWildcardAndStopCodon.json, lapis-e2e/test/aminoAcidInsertions.spec.ts, lapis/README.md, lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
Resolves #1105
Escapes the stop codon correctly, when passing it to SILO. 
=> fix(lapis): pass correctly escaped stop codon to SILO

lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
=> feat(lapis): return empty lineage definitions when SILO returns an empty file

.idea/runConfigurations/LapisOpen.xml, lapis-docs/src/content/docs/concepts/request-methods.mdx, lapis-e2e/test/aggregated.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/request/Field.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
I also did some more research. I's a bit unclear how arrays should actually be supplied, some sources also mentioned `fields=value1,value2`. Spring itself does not accept this, so I guess it's ok that we also don't accept it.
resolves #1089
=> fix(lapis-docs): mention how arrays must be supplied in form urlencoded requests

lapis-e2e/test/details.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponseStreamer.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/ResponseCollections.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/Helpers.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDataFormatTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDownloadAsFileTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt, lapis/src/test/resources/config/testDatabaseConfig.yaml
=> fix(lapis): also return CSV header when there are no data

lapis-e2e/test/aminoAcidMutations.spec.ts, lapis-e2e/test/nucleotideMutations.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/Field.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/ResponseCollections.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/Helpers.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDataFormatTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/request/MutationProportionsRequestTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/response/MutationResponseTest.kt
If `fields` is not empty, then the response will only contain the fields that were specified there.
resolves #1092
=> feat(lapis): add `fields` property to mutation endpoints

lapis-e2e/test/aminoAcidMutations.spec.ts, lapis-e2e/test/nucleotideMutations.spec.ts
I think this was introduced by first merging #1149 (which added the tests) and then merging a non-rebased #1135 (which changed the open api generator version).
resolves #
=> test(lapis-e2e): fix mutation e2e tests

lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
=> fix(lapis): add missing `dataFormat` to amino acid mutation GET endpoint in Swagger UI

lapis-e2e/test/alignedNucleotideSequence.spec.ts, lapis-e2e/test/aminoAcidInsertions.spec.ts, lapis-e2e/test/aminoAcidSequence.spec.ts, lapis-e2e/test/details.spec.ts, lapis-e2e/test/nucleotideInsertions.spec.ts, lapis-e2e/test/unalignedNucleotideSequence.spec.ts, lapis/docker-compose.yml
resolves https://github.com/GenSpectrum/LAPIS/issues/1162
=> fix(lapis-e2e): remove tests that rely on order without specifying lapis to sort output

lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/CompressionFilter.kt
resolves #
When building we get a compiler error:
```
Override 'fun getContentLength(str: String, contentType: MediaType?): Long?' has incorrect nullability in its signature compared to the overridden declaration 'fun getContentLength(str: String, contentType: MediaType?): Long'
```
The original method is declared in Java as returning Long (boxed), not long (primitive).
In Java, Long can be null, which aligns with the method docstring: "Returns the content length... or null if not known."
However, Kotlin treats Java’s boxed Long (java.lang.Long) as Long!, which is platform-typed — and when you override such a method, you must match the signature exactly, not make it more nullable.
=> fix(lapis): fix compiler warning

lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
and if it ever is, let's rather accept the null pointer exception rather than silently ignoring user input
=> chore(lapis): the antlr context should never be null

lapis/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt, lapis/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
We don't know yet whether we want to handle that as a "bad request" at this point.
=> refactor(lapis): it's cleaner to hand out `null` when getting an unknown sequence from the reference genome

.commitlintrc.js, lapis-docs/src/components/FiltersTable/getFilters.tsx, lapis-docs/src/components/QueryGenerator/FiltersSelection.tsx, lapis-docs/src/config.ts, lapis-docs/src/content/docs/concepts/string-search.mdx, lapis-docs/src/content/docs/maintainer-docs/references/database-configuration.mdx, lapis-e2e/test/aggregated.spec.ts, lapis-e2e/testData/multiSegmented/testDatabaseConfig.yaml, lapis-e2e/testData/singleSegmented/protectedTestDatabaseConfig.yaml, lapis-e2e/testData/singleSegmented/testDatabaseConfig.yaml, lapis/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt, lapis/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfigValidator.kt, lapis/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt, lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt, lapis/src/test/kotlin/org/genspectrum/lapis/DummyDatabaseConfig.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigValidatorTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt
BREAKING CHANGE: `lapisAllowsRegexSearch` on string metadata fields in the database config is not necessary anymore, regex search is always enabled for all string fields.
resolves #1175
=> feat(lapis): allow regex search for all string fields by default

lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt
I accidentally found this while doing #1194 
e.g. dates don't allow regex search, thus `isNull(date.regex)` should be rejected
=> fix(lapis): advanced queries: disallow `isNull(<fieldName>.regex)` for all field types

.github/workflows/lapis.yml, lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt
also refactor the test to make it easier to grasp what is already tested
resolves #1187
=> fix(lapis): advanced queries: make `.regex` case-insensitive

.github/workflows/lapis.yml, lapis-e2e/README.md, lapis-e2e/generateOpenApiClients.sh, lapis-e2e/test/aggregated.spec.ts, lapis-e2e/test/aggregatedQueries/aggregrationFields.json, lapis-e2e/test/aggregatedQueries/groupByBoolean.json, lapis-e2e/test/aminoAcidMutations.spec.ts, lapis-e2e/test/details.spec.ts, lapis-e2e/test/nucleotideInsertions.spec.ts, lapis-e2e/test/nucleotideMutations.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
in #1135 we upgraded to org.springdoc:springdoc-openapi-starter-webmvc-ui 2.8.6. Since version 2.8.0, they use OpenAPI version 3.1 as default which was breaking for us, because the generated spec didn't look as expected anymore
resolves #1193
=> fix(lapis): fix Swagger UI layout of GET requests

lapis-e2e/test/unalignedNucleotideSequence.spec.ts, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
since we don't want to support it anymore.
This is kind of breaking (in the docs), but the functionality didn't change, so I didn't label it as a breaking change.
resolves #1248
=> feat(lapis): drop sorting by segment/gene from docs of sequence endpoints

lapis/src/main/kotlin/org/genspectrum/lapis/config/AccessKeys.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt, lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloUris.kt, lapis/src/test/kotlin/org/genspectrum/lapis/SwaggerUiTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/InfoControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LandingPageControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDataFormatTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDownloadAsFileTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerPhyloTreeTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MutationsOverTimeControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/response/MutationResponseTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
It said:
"This annotation is currently applied to the value parameter only, but in the future it will also be applied to field.
- To opt in to applying to both value parameter and field, add '-Xannotation-default-target=param-property' to your compiler arguments.
- To keep applying to the value parameter only, use the '@param:' annotation target."
https://youtrack.jetbrains.com/issue/KT-73255
=> chore(lapis): fix compiler warnings

lapis/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/MutationsOverTimeController.kt
The mutations over time endpoints should only require `aggregatedDataAccessKeys` for non-open instances.
- ~[ ] All necessary documentation has been adapted.~
- ~[ ] The implemented feature is covered by an appropriate test.~
=> fix(lapis): mutations over time need only aggregatedDataAccessKey

lapis-docs/src/content/docs/concepts/response-format.mdx, lapis/src/main/kotlin/org/genspectrum/lapis/controller/Headers.kt, lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DataFormatParameterFilter.kt, lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt, lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponseStreamer.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDataFormatTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/response/CsvWriterTest.kt
resolves #1283 
Adds a new `IanaTsvWriter`, which escapes new lines and delimiters in cell values, and doesn't do any quoting. Configuring the `CsvPrinter` used in the `CsvWriter` - instead of creating a new class - didn't work: Setting the `QuoteMode`, to `NONE` quotes newlines and delimiters, but the tab was quoted as `\\\t`, which isn't right. I tried working around this, but in the end decided it was cleaner to write a quick implementation of the IANA spec from scratch, instead of trying to get the Apache lib to work with the format which it wasn't designed to support.
I've called the new type "TSV-ESCAPED". The RFC4180 already calls the quote-mechanism escaping, but I'd argue that's not escaping, that's quoting. Instead the new behaviour is escaping. This is now a new datatype, like …
=> feat(lapis): support TSV with escaped special characters

lapis/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
The request mentioned in #1324 had a gigantic error message because it contained the whole newick tree that was too large for Jackson to parse. 100k chars should still be enough for any reasonable error message.
This is the current error message (the part that fits on a screenshot):
=> fix(lapis): truncate error details if they are too long

lapis/src/main/kotlin/org/genspectrum/lapis/model/mutationsOverTime/MutationsOverTimeModel.kt, lapis/src/test/kotlin/org/genspectrum/lapis/controller/MutationsOverTimeControllerTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/AminoAcidMutationsOverTimeModelTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/Helpers.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/NucleotideMutationsOverTimeModelTest.kt
resolves #1308 
This PR modifies the `mutationsOverTime` response to also include the totalCount for the dateRange for every cell. This information is needed for the component, and with this information in the response, less queries are needed in the frontend.
=> feat(lapis): mutationsOverTime endpoint: return total sequence count per dateRange

lapis/src/main/kotlin/org/genspectrum/lapis/model/mutationsOverTime/MutationsOverTimeModel.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/AminoAcidMutationsOverTimeModelTest.kt, lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/NucleotideMutationsOverTimeModelTest.kt
In https://github.com/GenSpectrum/LAPIS/pull/1352 we made the thread count for the SILO client configurable, so we wouldn't get issues with creating too many threads and getting a RejectedExecutionException. But now we get the same issue, further up the call chain.
The `ForkJoinPool` used by the `parallelStream` will get blocked threads because of the `SiloClient`, and then creates compensation threads, eventually running into the thread limit, if there are a lot of mutations to query.
This PR removes the `parallelStream` in favor of a fixed size thread pool. It reuses the thread count from the SILO client, because that's the limiting factor anyways. The thread pool is created as a class property and maintained until the class is destroyed.
- ~~All necessary documentation has been …
=> fix(lapis): fix 500 server error in *mutationsOverTime endpoints
