GenSpectrum/LAPIS

- server/src/main/java/ch/ethz/lapis/api/query/Database.java
This closes #31 and should also fix https://github.com/GenSpectrum/cov-spectrum-website/issues/456
> feat: load columnar sequences to RAM

- server/src/main/java/ch/ethz/lapis/api/entity/res/CsvSerializer.java
> fix: CSV/TSV formatting is not working for mutations endpoints

- api-tests/package-lock.json
- api-tests/package.json
Update the URLs so that the tests run (but are not green though).
> fix URLs in JS api tests

- server/src/main/java/ch/ethz/lapis/api/SampleService.java
- server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleController.java
- server/src/main/java/ch/ethz/lapis/api/entity/AggregationFieldListDeserializer.java
- server/src/main/java/ch/ethz/lapis/api/entity/DetailsField.java
- server/src/main/java/ch/ethz/lapis/api/entity/DetailsFieldListDeserializer.java
- server/src/main/java/ch/ethz/lapis/api/entity/EnumFieldListDeserializer.java
- server/src/main/java/ch/ethz/lapis/api/entity/req/BaseSampleRequest.java
- server/src/main/java/ch/ethz/lapis/api/entity/req/MutationRequest.java
- server/src/main/java/ch/ethz/lapis/api/entity/req/SampleDetailRequest.java
- server/src/main/java/ch/ethz/lapis/api/entity/res/SampleDetail.java
- server/src/main/java/ch/ethz/lapis/api/query/QueryEngine.java
- server/src/test/java/ch/ethz/lapis/api/controller/v1/GisaidSampleControllerTest.java
- server/src/test/java/ch/ethz/lapis/api/controller/v1/OpenSampleControllerTest.java
- server/src/test/java/ch/ethz/lapis/api/entity/DetailsFieldTest.java
- server/src/test/java/ch/ethz/lapis/api/log/RequestContextLoggerFilterTest.java
> Specify "fields" that should be returned by the /details endpont

- server/src/main/java/ch/ethz/lapis/api/SampleService.java
- server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleController.java
- server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleResponseBuilder.java
- server/src/main/java/ch/ethz/lapis/api/entity/req/OrderAndLimitConfig.java
- server/src/main/java/ch/ethz/lapis/source/gisaid/BatchProcessingWorker.java
- server/src/main/java/ch/ethz/lapis/source/ng/NextstrainGenbankMutationAAWorker.java
- server/src/main/java/ch/ethz/lapis/source/ng/NextstrainGenbankService.java
- server/src/main/java/ch/ethz/lapis/util/FastaEntry.java
- server/src/test/java/ch/ethz/lapis/api/controller/v1/GisaidSampleControllerTest.java
- server/src/test/java/ch/ethz/lapis/api/controller/v1/OpenSampleControllerTest.java
> AA sequences endpoint

- server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleResponseBuilder.java
- server/src/test/java/ch/ethz/lapis/api/controller/v1/OpenSampleControllerTest.java
> Fix: Charset wrongly interpreted (at least for TSV output)

- docs/developer/LAPIS.puml
- docs/developer/architectural_overview.md
This is a draft to roughly sketch the dependencies between various data sources and artifacts. Feedback is welcome, this is supposed to be extended.
> docs: Document architecture of LAPIS and surroundings

- lapis2/README.md
- lapis2/build.gradle
- lapis2/src/main/resources/application.properties
> docs: autogenerate OpenAPI docs

- lapis2/.editorconfig
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/AggregatedModelTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloFilterTest.kt
> Implement SILO queries for metadata columns

- .github/workflows/lapis2.yml
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/main/resources/public/error/404.html
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- siloLapisTests/.mocharc.json
- siloLapisTests/.prettierignore
- siloLapisTests/.prettierrc.json
- siloLapisTests/package-lock.json
- siloLapisTests/package.json
- siloLapisTests/test/common.ts
- siloLapisTests/test/example.spec.ts
- siloLapisTests/test/unknownUrl.spec.ts
- siloLapisTests/tsconfig.json
Resolves #184
"make sure we get proper 400 errors when sending bad requests." is not included because we can not send bad requests yet and therefore can not be tested. Will be a new ticket.
> Implement Error Handling

- lapis2/build.gradle
- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/logging/RequestContext.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/logging/StatisticsLogObjectMapper.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/util/TimeFactory.kt
- lapis2/src/main/resources/logback.xml
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/logging/RequestContextLoggerTest.kt
resolves #135 
This is mainly copied from the old LAPIS.
> Implement logging and gather usage statistics

- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/AccessKeys.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/util/CachedBodyHttpServletRequest.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/util/YamlObjectMapper.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/GisaidAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/AccessKeysReaderTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt
- lapis2/src/test/resources/application-testWithoutAccessKeys.properties
- lapis2/src/test/resources/config/gisaidDatabaseConfig.yaml
- lapis2/src/test/resources/config/protectedDataDatabaseConfig.yaml
- lapis2/src/test/resources/config/testAccessKeys.yaml
- lapis2/src/test/resources/config/testDatabaseConfig.yaml
- lapis2/src/test/resources/config/testDatabaseConfigWithoutFeatures.yaml
- siloLapisTests/testDatabaseConfig.yaml
> Access key authentication

- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
- siloLapisTests/test/aggregatedQueries/pangoLineageIsB_1_1_7endingWithDotIncludingSublineages.json
- siloLapisTests/test/aggregatedQueries/pangoLineageIsB_1_1_7includingSublineages.json
- siloLapisTests/testDatabaseConfig.yaml
due to https://github.com/GenSpectrum/LAPIS-SILO/pull/116
> tests: fix pango lineage related tests

- .github/workflows/lapis2.yml
See https://github.com/GenSpectrum/servers/pull/3#discussion_r1219870480
> build: also publish a "latest" Docker image on builds of the main branch

- lapis2/src/main/kotlin/org/genspectrum/lapis/request/DataVersion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- siloLapisTests/test/aggregated.spec.ts
- siloLapisTests/test/details.spec.ts
- siloLapisTests/test/nucleotideMutations.spec.ts
> 272 return the data version

- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisResponse.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- siloLapisTests/test/aggregated.spec.ts
- siloLapisTests/test/details.spec.ts
- siloLapisTests/test/nucleotideMutations.spec.ts
> feat: wrap response data to match LAPIS 1 structure (#324)

- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CsvWriter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
- siloLapisTests/test/aggregated.spec.ts
- siloLapisTests/test/aggregatedQueries/aggregrationFields.json
> enable /aggregated to return the data as CSV

- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/MutationProportionsRequestTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
- siloLapisTests/test/aminoAcidMutations.spec.ts
> Aa mutations endpoint

- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- siloLapisTests/test/aminoAcidMutations.spec.ts
- siloLapisTests/test/nucleotideMutations.spec.ts
Resolves #206
This PR also includes csv/tsv return value for aminoAcidMutations endpoint
> Implement returning csv in the nucleotidemutations endpoint

- lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/SingleSegmentedSequenceFeature.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/InsertionsRequest.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/DatabaseConfigTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/SingleSegmentedSequenceFeatureTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
- lapis2/src/test/resources/config/testDatabaseConfig.yaml
- siloLapisTests/test/aggregated.spec.ts
- siloLapisTests/test/aminoAcidInsertions.spec.ts
- siloLapisTests/test/aminoAcidMutations.spec.ts
- siloLapisTests/test/details.spec.ts
- siloLapisTests/test/nucleotideInsertions.spec.ts
- siloLapisTests/test/nucleotideMutations.spec.ts
- siloLapisTests/testData/testDatabaseConfig.yaml
> Add nucleotideInsertions endpoint returning json,csv and tsv

- .github/workflows/lapis2-docs.yml
- lapis2-docs/.dockerignore
- lapis2-docs/Dockerfile
- lapis2-docs/test-docker-compose.yml
> build(lapis2-docs): build Docker image

- .idea/runConfigurations/LapisV2Open.xml
- .idea/runConfigurations/LapisV2Protected.xml
- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/OrderByField.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/MutationProportionsRequestTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
- lapis2/src/test/resources/logback-test.xml
Try to pass on errors from SILO if possible.
> Pass on silo errors

- lapis2/src/main/resources/logback.xml
https://github.com/pathoplexus/pathoplexus/issues/455
> feat: also write logs to stdout

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/DataVersion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceControllerTest.kt
> Add info to lapis response

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- siloLapisTests/test/aminoAcidSequence.spec.ts
Resolves #436 
Merge this only, if PR on other repo is fixed.
> refactor: rename 'amino acid sequence' to 'aligned amino acid sequence'

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/InfoController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/InfoControllerTest.kt
> feat: add info controller

- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
Don't consider the full "requestURI" as this might contain a prefix that a proxy sets.
> fix: consider only servlet URL when checking auth

- lapis2/src/main/antlr/org/genspectrum/lapis/model/variantqueryparser/VariantQuery.g4
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/CovidSpecifics.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
- siloLapisTests/test/details.spec.ts
- siloLapisTests/testData/small_metadata_set.tsv
- siloLapisTests/testData/testDatabaseConfig.yaml
> feat: implement leftover variant query parts

- lapis2/src/main/kotlin/org/genspectrum/lapis/config/SequenceFilterFields.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/CaseInsensitiveFieldsCleaner.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/Field.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/OrderByField.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/DummySequenceFilterFields.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/SequenceFilterFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFieldsTest.kt
> feat: make fields case-insensitive

- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidMutationTest.kt
> fix: allow stop codon symbol for AminoAcidMutations

- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideInsertionTest.kt
> feat: allow lower case for insertions

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/MutationProportionsRequest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/MutationProportionsRequestTest.kt
See https://github.com/GenSpectrum/LAPIS-SILO/pull/234
> fix: set default min proportion

- lapis2/src/main/antlr/org/genspectrum/lapis/model/variantqueryparser/VariantQuery.g4
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryFacade.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
> Lower case letters for mutations and insertions in variant queries

- lapis2/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/MutationProportionsRequestTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFieldsTest.kt
> Allow lower case letters for genes in aminoacidmutation and aminoacidinsertion requests

- lapis2-docs/.env.example
- lapis2-docs/Dockerfile
- lapis2-docs/README.md
- lapis2-docs/package-lock.json
- lapis2-docs/package.json
- lapis2-docs/src/components/QueryGenerator/QueryGenerator.tsx
- lapis2-docs/src/components/QueryGenerator/QueryTypeSelection.tsx
- lapis2-docs/src/components/QueryGenerator/QueryTypeSelectionState.ts
- lapis2-docs/src/components/QueryGenerator/Result.tsx
- lapis2-docs/src/content/docs/getting-started/generate-your-request.mdx
- lapis2-docs/src/reference_genomes.ts
- lapis2-docs/test-docker-compose.yml
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
> docs: prepend the url to the instance and handle multi segmented case

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ErrorController.kt
> feat: show instance name on "not found" page

- .github/workflows/lapis2-docs.yml
- lapis2-docs/.gitignore
- lapis2-docs/.prettierrc
- lapis2-docs/astro.config.mjs
- lapis2-docs/package-lock.json
- lapis2-docs/package.json
- lapis2-docs/playwright.config.ts
- lapis2-docs/src/content/docs/architecture-and-dev-docs/architecture-and-constraints.mdx
- lapis2-docs/src/content/docs/architecture-and-dev-docs/glossary.mdx
- lapis2-docs/src/content/docs/architecture-and-dev-docs/introduction.mdx
- lapis2-docs/src/content/docs/architecture-and-dev-docs/system-scope-and-context.mdx
- lapis2-docs/src/content/docs/getting-started/generate-your-request.mdx
- lapis2-docs/src/content/docs/getting-started/introduction.mdx
- lapis2-docs/test-docker-compose.yml
- lapis2-docs/tests/docs.spec.ts
- lapis2-docs/tests/queryGenerator.page.ts
- lapis2-docs/tests/queryGenerator.spec.ts
- lapis2-docs/tsconfig.json
> tests(docs): implement some basic playwright tests

- lapis2-docs/src/components/SwaggerUIContainer.astro
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
> docs: update mutation description

- lapis2-docs/astro.config.mjs
- lapis2-docs/package-lock.json
- lapis2-docs/package.json
- lapis2-docs/src/components/DatabaseConfig.astro
- lapis2-docs/src/components/ReferenceGenome.astro
- lapis2-docs/src/content/docs/references/database-config.mdx
- lapis2-docs/src/content/docs/references/reference-genome.mdx
- lapis2-docs/tests/docs.spec.ts
- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisApplication.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/InfoController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryFacade.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/ReferenceGenomeTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/InfoControllerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloQueryModelTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
- lapis2/src/test/resources/application-test.properties
- lapis2/src/test/resources/application-testWithoutAccessKeys.properties
> Expose configuration

- .idea/runConfigurations/lapis2_docs.xml
> build: add intelliJ run configuration for lapis2 docs

- lapis2-docs/astro.config.mjs
- lapis2-docs/src/components/MutationFilters/MaybeAminoAcidMutationExample.astro
- lapis2-docs/src/content/docs/architecture-and-dev-docs/99-glossary.mdx
- lapis2-docs/src/content/docs/concepts/ambiguous-symbols.mdx
- lapis2-docs/src/content/docs/concepts/mutation-filters.mdx
- lapis2-docs/src/content/docs/concepts/variant-query.mdx
- lapis2-docs/tests/docs.spec.ts
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapper.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/MaybeMutationWrapper.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/SiloFilterExpressionMapperTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidMutationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideMutationTest.kt
- siloLapisTests/test/aggregatedQueries/maybeAminoAcidMutation.json
- siloLapisTests/test/aggregatedQueries/maybeNucleotideMutation.json
resolves #551 
transferring https://github.com/GenSpectrum/LAPIS/wiki/4.5-Ambiguous-symbols
> feat(docs): transfer ambiguous symbols explanation #551

- lapis2/src/main/antlr/org/genspectrum/lapis/model/variantqueryparser/VariantQuery.g4
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
> fix: variant query with nextcladePangolineageQuery

- lapis2-docs/astro.config.mjs
- lapis2-docs/src/content/docs/concepts/ambiguous-symbols.mdx
- lapis2-docs/src/content/docs/maintainer-docs/references/reference-genomes.mdx
- lapis2-docs/src/content/docs/references/nucleotide-and-amino-acid-symbols.mdx
- lapis2-docs/src/content/docs/references/reference-genomes.mdx
- lapis2-docs/tests/docs.spec.ts
resolves #573
- ~~[The implemented feature is covered by an appropriate end-to-end test.~~
> feat(docs): list valid nucleotide and amino acid symbols

- lapis2-docs/astro.config.mjs
- lapis2-docs/src/content/docs/maintainer-docs/references/preprocessing.mdx
- lapis2-docs/src/content/docs/maintainer-docs/references/starting-silo-and-lapis.mdx
- lapis2-docs/tests/docs.spec.ts
resolves #569 #570
- ~~The implemented feature is covered by an appropriate end-to-end test.~~
> feat(docs): reference how to start LAPIS and SILO

- lapis2-docs/src/components/TsvExample.astro
- lapis2-docs/src/content/docs/maintainer-docs/references/preprocessing.mdx
- lapis2-docs/src/content/docs/maintainer-docs/references/starting-silo-and-lapis.mdx
- lapis2-docs/src/content/docs/maintainer-docs/tutorials/start-lapis-and-silo.mdx
resolves #565
- ~~The implemented feature is covered by an appropriate end-to-end test.~~
> feat(docs): document how to provide data to the SILO preprocessing

- lapis2-docs/astro.config.mjs
- lapis2-docs/src/components/QueryGenerator/QueryTypeSelection.tsx
- lapis2-docs/src/content/docs/getting-started/introduction.mdx
- lapis2-docs/src/content/docs/references/introduction.mdx
- lapis2-docs/src/content/docs/references/nucleotide-and-amino-acid-symbols.mdx
- lapis2-docs/tests/docs.spec.ts
> fix(docs): some minor improvements

- lapis2/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/request/NucleotideInsertionTest.kt
> feat: amino acid and nucleotide insertion filters are case-insensitive

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DownloadAsFileFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SampleRoute.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SpecialProperties.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/DownloadAsFileParameterCustomizer.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OperationsSorter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/request/LapisInfo.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCommonFieldsTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/openApi/OperationsSorterTest.kt
- siloLapisTests/test/aggregated.spec.ts
resolves #599
- ~~[ ] All necessary documentation has been adapted.~~ #604
> feat: implement downloadAsFile

- .idea/runConfigurations/LapisV2Protected.xml
- lapis2-docs/src/components/ConfigGenerator/AdditionalInformationWizard.tsx
- lapis2-docs/src/components/ConfigGenerator/MetadataWizard.tsx
- lapis2-docs/src/components/ConfigGenerator/UploadConfig.tsx
- lapis2-docs/src/components/ConfigGenerator/configContext.tsx
> fix(docs): schema for uploaded config

- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DownloadAsFileFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/util/CachedBodyHttpServletRequest.kt
> fix: recognition of which endpoint was called to determine the filename of a download

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CsvWriter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- siloLapisTests/test/details.spec.ts
> implement the header parameter "headers=false" to disable the header in the returned CSV/TSV

- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/DownloadAsFileParameterCustomizer.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- siloLapisTests/test/requestId.spec.ts
> fix: remove request id header -> make Swagger UI work again

- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/AccessKeyParameterCustomizer.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
resolves #632 
~~- [ ] The implemented feature is covered by an appropriate end-to-end test.~~
> feat: add access key parameter to /sample/info and remove downloadAsFile

- lapis2-docs/playwright.config.ts
- lapis2-docs/src/content/docs/concepts/pango-lineage-query.mdx
- lapis2-docs/src/content/docs/concepts/response-format.md
- lapis2-docs/src/content/docs/concepts/variant-query.mdx
- lapis2-docs/src/content/docs/getting-started/introduction.mdx
- lapis2-docs/tests/docs.spec.ts
resolves #603 
~~- [ ] The implemented feature is covered by an appropriate end-to-end test.~~
> test: visit each page on its own in test for relative links

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt
> feat: return bad request error when unknown compression format in request

- lapis2/src/main/kotlin/org/genspectrum/lapis/auth/DataOpennessAuthorizationFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/config/AccessKeys.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/auth/ProtectedDataAuthorizationTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/config/AccessKeysReaderTest.kt
- lapis2/src/test/resources/config/testAccessKeys.yaml
> feat: use multiple access keys

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
> feat: forward Retry-After header when SILO is not available yet

- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
Related to https://github.com/GenSpectrum/LAPIS-SILO/issues/303
> Request id for silo

- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/CompressionFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DataFormatParameterFilter.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/util/ResponseWithContentType.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
- siloLapisTests/test/details.spec.ts
resolves https://github.com/GenSpectrum/cov-spectrum-website/issues/930
> feat: change content type to text/plain when asking for csv/tsv without headers

- lapis2-docs/astro.config.mjs
- lapis2-docs/src/components/CacheSizeEndpointLink.astro
- lapis2-docs/src/content/docs/maintainer-docs/concepts/caching.mdx
- lapis2-docs/tests/docs.spec.ts
> document caching

- lapis2-docs/src/content/docs/references/additional-request-properties.mdx
- lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/scheduler/DataVersionCacheInvalidator.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
- siloLapisTests/test/details.spec.ts
> feat: support order by random

- lapis2-docs/src/content/docs/maintainer-docs/concepts/caching.mdx
- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloQuery.kt
- lapis2/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
> feat: try whether also caching aggregated queries makes cov spectrum faster

- .github/workflows/lapis2.yml
- lapis2/.dockerignore
- lapis2/Dockerfile
- lapis2/build.gradle
> multi architecturearm docker support

- .commitlintrc.js
- .github/dependabot.yml
- .github/workflows/commitlint.yml
- package-lock.json
- package.json
> build(root): use commitlint to enforce conventional commits

- lapis2-docs/src/components/RenderedExampleForm.astro
- lapis2-docs/src/content/docs/concepts/request-methods.mdx
> feat(lapis2-docs): document url encoded forms

- lapis2-docs/.prettierignore
> build(lapis2-docs): make prettier ignore CHANGELOG since it's autogenerated

- .github/workflows/release-lapis2.yml
> build(github-actions): when releasing, just check whether any release was created

- release-please-config.json
`..` is special syntax for "recursive descent".
https://goessner.net/articles/JsonPath/
> build(github-actions): fix jsonpath for empty string

- lapis2/Dockerfile
This helps downstream users, e.g. by allowing them to enable dependabot to create update PRs.
See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#docker
> chore(Dockerfile): Add opencontainers.image.source label

- lapis2/src/main/kotlin/org/genspectrum/lapis/LapisSpringConfig.kt
- siloLapisTests/test/requestId.spec.ts
> fix(lapis2): bring back request id header in OpenAPI docs

- lapis2/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
> fix(lapis2): also log which line of the SILO response failed to parse

- lapis2/src/main/resources/logback.xml
Seems like this accidentally got lost in commit 6afca1a7b9cc06b1459803e0a471b774f9e9a26a (#692)
resolves #
> fix(lapis2): log request id again

- .github/scripts/preview-changelog.sh
- .github/workflows/changelog-preview.yml
- package.json
> Changelog preview

- .idea/runConfigurations/lapis_docs.xml
- lapis-docs/src/components/ConfigGenerator/configContext.tsx
> fix(docs): Config generator: dateToSortBy, partitionBy and features is optional

- lapis-docs/src/content/docs/references/additional-request-properties.mdx
- lapis-e2e/test/common.spec.ts
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DownloadAsFileFilter.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/SampleEndpointsGetParameterCustomizer.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/SpecialProperties.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDownloadAsFileTest.kt
Resolves #869
Proof of concept, would be great if someone with more experience with the code base could finish it by sorting out tests. Thanks!
How do you test these things other than using unit/e2e tests? Do you have a test deployment with some basic test data? That'd be cool :)
> feat: allow customizable filename for file downloads

- lapis/src/main/kotlin/org/genspectrum/lapis/controller/Headers.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DownloadAsFileFilter.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCompressionTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDownloadAsFileTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/MockData.kt
> fix(lapis): fix download file ending for csv-without-headers data format

- lapis-docs/astro.config.mjs
- lapis-docs/src/components/FiltersTable/FiltersTable.astro
- lapis-docs/src/components/FiltersTable/getFilters.tsx
- lapis-docs/src/components/QueryGenerator/FiltersSelection.tsx
- lapis-docs/src/components/QueryGenerator/QueryTypeSelectionState.ts
- lapis-docs/src/config.ts
- lapis-docs/src/content/docs/concepts/string-search.mdx
- lapis-docs/src/utils/code-generators/python/generator.ts
- lapis-docs/src/utils/code-generators/types.ts
- lapis-docs/tests/docs.spec.ts
- lapis-docs/tests/queryGenerator.page.ts
resolves #900
This PR adds the documentation of the string search feature in LAPIS.
> docs(lapis): document string search feature

- lapis/src/main/kotlin/org/genspectrum/lapis/controller/LandingPageController.kt
> feat(lapis): add instance name to landing page json

- lapis/Dockerfile
- lapis/src/main/resources/application.properties
> feat(lapis): add healthcheck to Docker containers

- .commitlintrc.js
- lapis-e2e/test/aggregated.spec.ts
- lapis-e2e/test/details.spec.ts
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/SequenceFiltersRequestWithFields.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerCsvTest.kt
resolves #910
-  OpenAPI specs have been adapted.
> feat(lapis): order CSV/TSV columns of aggregated/details data as specified in the request fields or as in the database config

- .github/workflows/changelog-preview.yml
We copied this from the components to SILO a while ago, but not yet to LAPIS. I think it has proven itself as good enough so that we can also use it here.
> ci(github-actions): improve messages on the generated changelog previews

- README.md
> docs(root): link to docs of the open covid instance in README

- lapis/docker-compose.yml
See https://github.com/GenSpectrum/LAPIS-SILO/pull/633
resolves #
> test(lapis-e2e): adapt SILO to 0.5.0 changes

- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
> fix(lapis): fix description of mutation objects in OpenApi spec

- README.md
- lapis-e2e/test/info.spec.ts
- lapis/src/main/kotlin/org/genspectrum/lapis/config/SiloVersion.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/InfoController.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisInfoFactory.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/scheduler/DataVersionCacheInvalidator.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/InfoControllerTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloClientTest.kt
related to https://github.com/GenSpectrum/LAPIS-SILO/issues/604
> feat(lapis): add `siloVersion` to response info

- .gitignore
- lapis-e2e/README.md
- lapis/README.md
resolves https://github.com/GenSpectrum/LAPIS/issues/1113
> docs(lapis): improve local testing documentation

- .idea/runConfigurations/LapisOpen.xml
- lapis-docs/astro.config.mjs
- lapis-docs/src/components/MutationFilters/AminoAcidInsertionExample.astro
- lapis-docs/src/components/MutationFilters/AminoAcidMutationExample.astro
- lapis-docs/src/components/MutationFilters/NucleotideInsertion.astro
- lapis-docs/src/components/MutationFilters/NucleotideInsertionExample.astro
- lapis-docs/src/components/MutationFilters/NucleotideMutationsExample.astro
- lapis-docs/src/components/MutationFilters/SegmentNames.astro
- lapis-docs/src/content/docs/concepts/insertion-filters.mdx
- lapis-docs/src/content/docs/concepts/mutation-filters.mdx
- lapis-docs/tests/docs.spec.ts
- lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithStopCodon.json
- lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithWildcard.json
- lapis-e2e/test/aggregatedQueries/aminoAcidInsertionWithWildcardAndStopCodon.json
- lapis-e2e/test/aminoAcidInsertions.spec.ts
- lapis/README.md
- lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/model/VariantQueryFacadeTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/request/AminoAcidInsertionTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/silo/SiloQueryTest.kt
> 594 docs add description of insertions filters

- lapis-docs/astro.config.mjs
- lapis-docs/package-lock.json
- lapis-docs/package.json
resolves #1124 
We now need to allow all hosts in astro config.
I tested it on staging and it works there. 
> 1124 docs dont allow our host anymore

- lapis/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidInsertion.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/AminoAcidMutation.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/NucleotideInsertion.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
Suggested in https://github.com/GenSpectrum/LAPIS/pull/1116#discussion_r2002997084 as a refactor to make code clearer
> feat(lapis): refactor getNucleotideSequenceFromLowercaseName and getGeneFromLowercaseName to do case conversion in function

- lapis/src/main/kotlin/org/genspectrum/lapis/controller/ExceptionHandler.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/model/VariantQueryCustomListener.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/ExceptionHandlerTest.kt
I found this while reviewing #1144
> refactor(lapis): remove unused exception

- lapis-docs/src/content/docs/concepts/variant-query.mdx
> fix(lapis-docs): fix condition when to show the "variant queries are not available" banner

- CONTRIBUTING.md
- README.md
> docs(root): add CONTRIBUTING.md with developers docs

- lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt
I found it annoying during testing that it didn't tell me what is available.
> fix(lapis): advanced queries: tell which metadata fields exist when finding an unknown one

- lapis/src/main/kotlin/org/genspectrum/lapis/config/ReferenceGenome.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/ControllerDescriptions.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/controller/MutationsOverTimeController.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/model/MutationValidator.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/model/mutationsOverTime/MutationsOverTimeModel.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/openApi/Schemas.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/CommonSequenceFilters.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/MutationsOverTimeRequest.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/request/NucleotideMutation.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/LapisResponse.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/controller/MutationsOverTimeControllerTest.kt
- lapis/src/test/kotlin/org/genspectrum/lapis/model/mutationsOverTime/MutationsOverTimeModelTest.kt
resolves #1205
This adds the endpoints as discussed a while ago (notes in [Nuclino](https://app.nuclino.com/GenSpectrum/Development/2025-05-20-Mutations-over-time-API-1fa63034-e1ac-42db-97b0-085b2624ce98)).
> feat(lapis): add nucleotideMutationsOverTime endpoint

- lapis/src/main/kotlin/org/genspectrum/lapis/response/SiloResponse.kt
> chore(lapis): fix deprecation warning

- lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/model/SiloQueryModel.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/response/TreeStreamer.kt
> refactor(lapis): tiny clean ups

- lapis-e2e/test/common.ts
- lapis-e2e/test/mutationsOverTime.spec.ts
resolves #1208 
- ~~All necessary documentation has been adapted.~~
> test(lapis-e2e): add test for mutationsOverTime

- lapis-docs/src/content/docs/maintainer-docs/references/database-configuration.mdx
- lapis-e2e/testData/singleSegmented/testDatabaseConfig.yaml
- lapis/src/main/kotlin/org/genspectrum/lapis/config/DatabaseConfig.kt
- lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt
resolves #1348 
- ~~The implemented feature is covered by an appropriate test.~~
> feat(lapis): make thread count for SILO client configurable

- lapis/build.gradle
resolves https://github.com/GenSpectrum/LAPIS/issues/1391
> chore(lapis): fix build error, explicitly define dependencies

- .idea/runConfigurations/LapisOpen.xml
- .idea/runConfigurations/LapisProtected.xml
Some local adjustments my IDE made (on Mac OS) when running the project. Let's check whether they also work for @fengelniederhammer
> chore(build): slight adjustment of IntelliJ run configurations
